
  CREATE TABLE "NOVELPIA"."T_BOOK" 
   (	"U_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"WRITER_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"PUBLISHER_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"B_CODE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"AGE_LIMIT" NUMBER(4,0) NOT NULL ENABLE, 
	"BORROW_POINT" NUMBER(8,0) NOT NULL ENABLE, 
	"BUY_POINT" NUMBER(14,0) NOT NULL ENABLE, 
	"DATA_FILENAME" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"IMAGE_FILENAME" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"SCORE" FLOAT(126) DEFAULT 0, 
	"SCORE_GIVER_COUNT" NUMBER(14,0) DEFAULT 0, 
	 CONSTRAINT "BOOK_PK" PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
