
  CREATE TABLE "NOVELPIA"."T_MYBOOK" 
   (	"BOOK_UID" NUMBER(20,0) NOT NULL ENABLE, 
	"USER_UID" NUMBER(18,0) NOT NULL ENABLE, 
	"START_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
	 CONSTRAINT "MYBOOK_PK" PRIMARY KEY ("USER_UID", "BOOK_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MYBOOK_USER_FK" FOREIGN KEY ("USER_UID")
	  REFERENCES "NOVELPIA"."T_USER" ("U_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "MYBOOK_BOOK_FK" FOREIGN KEY ("BOOK_UID")
	  REFERENCES "NOVELPIA"."T_BOOK" ("U_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
