
  CREATE TABLE "NOVELPIA"."T_REVIEW_BOARD_LIKE" 
   (	"USER_UID" NUMBER(20,0), 
	"BOARD_UID" NUMBER(20,0), 
	"LIKE_DATE" DATE, 
	 CONSTRAINT "T_LIKE_PK" PRIMARY KEY ("USER_UID", "BOARD_UID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "T_LIKE_USER_FK" FOREIGN KEY ("USER_UID")
	  REFERENCES "NOVELPIA"."T_USER" ("U_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "T_LIKE_BOARD_FK" FOREIGN KEY ("BOARD_UID")
	  REFERENCES "NOVELPIA"."T_REVIEW_BOARD" ("U_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
