
  CREATE TABLE "NOVELPIA"."T_USE_POINT_LOG" 
   (	"USER_UID" NUMBER(18,0) NOT NULL ENABLE, 
	"USE_POINT" NUMBER(10,0) NOT NULL ENABLE, 
	"USE_DATE" DATE NOT NULL ENABLE, 
	"USE_CONTENT" VARCHAR2(150 BYTE), 
	"U_ID" NUMBER(21,0), 
	 PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "USE_POINT_LOG_USER_FK" FOREIGN KEY ("USER_UID")
	  REFERENCES "NOVELPIA"."T_USER" ("U_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
